os: osx
osx_image: xcode13.4
language: swift
script:
    - xcodebuild clean build test -project EssentailFeed/EssentailFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
    - xcodebuild clean build test -project EssentailFeed/EssentailFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO iphonesimultor -destination "platform=macOS Simulator,OS=15.5 name=iPhone 12" 
