name: CI

on:
  push:
    branches: [ masterCI ]
  pull_request:
    branches: [ masterCI ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/xcode_13.3.1.app
    
    - name: Build and test
      run: xcodebuild clean build test -project EssentailFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO
